# 're' is short for 'run example'

[alias]
re-poseidon = ["run", "--example", "poseidon", "--release", "--", "--json"]
re-trivial = ["run", "--example", "trivial", "--release", "--", "--json"]
re-merkle = ["run", "--example", "merkle", "--features", "merkle-tree-gadget", "--release", "--", "--json"]

re-cli = ["run", "--example", "cli", "--release", "--features", "merkle-tree-gadget", "--"]
re-cli-dhat = ["run", "--example", "cli", "--release", "--features", "dhat-heap", "--"]

re-kzg-merkle = ["run", "--example", "merkle-ipa", "--features", "merkle-tree-gadget", "--release", "--"]
re-ipa-merkle = ["run", "--example", "merkle-kzg", "--features", "merkle-tree-gadget", "--release", "--"]
